services:
  mock-toss:
    build:
      context: mock-toss
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - CHAOS_MODE=NORMAL
      - CHAOS_SLOW_MIN_MS=3000
      - CHAOS_SLOW_MAX_MS=10000
      - CHAOS_PARTIAL_FAILURE_RATE=50
